## Numpy Review

In [18]:
# Creating numpy arrays
import numpy as np

mat = np.zeros((10,)) # Vector (1 dimensional array) of 10 zeros

mat = np.ones((10,5)) # Matrix of ones with 10 rows and 5 columns

mat = np.random.random((10,5)) # Matrix of random values between 0 and 1.

vec = np.array([1,2,3]) # Creates a 1 dimensional array based on a list

In [6]:
# Getting information about numpy arrays

print(mat.shape) # Gets the shape (number of rows by number of columns) of a numpy array

print(mat.dtype) # Gets the data type of each element in the array

(10, 5)
float64


In [8]:
# Indexing an array

# Returns the first row of mat
print(mat[0]) 
print(mat[0].shape) 

# returns the first column of mat
print(mat[:,0]) 
print(mat[:,0].shape) 

# Returns the number in the first row and first column of mat
print(mat[1,1])
print(mat[1,1].shape) 

[0.19996496 0.36488777 0.2433725  0.50761023 0.91304322]
(5,)
[0.19996496 0.5554866  0.73260104 0.04557483 0.34652143 0.64503064
 0.20553431 0.35128063 0.21732206 0.23426446]
(10,)
0.7105885838456811
()


In [9]:
# Looping over all rows in a matrix

for row in mat:
    print(row.shape)

(5,)
(5,)
(5,)
(5,)
(5,)
(5,)
(5,)
(5,)
(5,)
(5,)


In [10]:
# Looping over all column in a numpy matrix

for col in mat.T:
    print(col.shape)

(10,)
(10,)
(10,)
(10,)
(10,)


In [11]:
# Take the transpose of a matrix
# i.e., flip the matricies columns and rows. 
# For example, mat[1,2] will be moved to mat[2,1]

trans_mat = mat.T

print("before: {} after: {}".format(mat[1,2],trans_mat[2,1]))

before: 0.41883318412844506 after: 0.41883318412844506


In [13]:
# Select a subset of columns/rows in a matrix

spec_rows = mat[[0,1], :] # returns the 1st and 2nd rows in mat
print(spec_rows.shape)


spec_cols = mat[:,[0,1]] # Returns the 1st and second columns in mat
print(spec_cols.shape)

(2, 5)
(10, 2)


In [17]:
# Subtract/add two matricies element wise

mat1 = np.ones((3,4))

mat2 = np.ones((3,4))*2 # 2 is multipled elelment-wise in mat2. So, every element is = 2

print(mat1)
print()
print(mat2)

print()
new_mat = mat1 - mat2 # subtract each element in mat1 by its respective element in mat2
print(new_mat)

print()
new_mat = mat1 + mat2 # add each element in mat1 by its respective element in mat2
print(new_mat)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]

[[-1. -1. -1. -1.]
 [-1. -1. -1. -1.]
 [-1. -1. -1. -1.]]

[[3. 3. 3. 3.]
 [3. 3. 3. 3.]
 [3. 3. 3. 3.]]


In [20]:
# Dot (inner) preoduct between 2 vectors


vec1 = np.array([1,2,3])

vec2 = np.array([4,5,6])

print(vec1.dot(vec2)) # Returns 1*4 + 2*5 + 3*6

#For element-wise vector multiplication use the * symbol
print(vec1 * vec2)

32
[ 4 10 18]


In [21]:
# vector matrix multiplication (see here for more info: https://mathinsight.org/matrix_vector_multiplication)

mat = np.random.random((3,5))

vec = np.random.random((3))

print(vec.dot(mat)) # Returns a vector of size 5

[1.22236953 1.04580811 0.59975244 1.32970279 1.32026535]
